### ISSUE TITLE
Login - internal server error

### ISSUE THREAD

**Issue by mscottco** [FrameOS/frameos#101]
I've tried to deploy frameos using the latest docker image to my synology but am having issues with login. The initial user/pass creation works but I get an "Internal server error" message on the login page. Using an incorrect username/password gives an 'Invalid username or password' message so I know the password is correct. Included below is an excerpt from the container logs.

Any advice if this is a bug or a me issue?

```
Traceback (most recent call last):
  File "/app/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 1508, in finalize_request
    response = self.process_response(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 2002, in process_response
    response = self.ensure_sync(func)(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/.venv/lib/python3.11/site-packages/flask_login/login_manager.py", line 459, in _update_remember_cookie
    self._set_cookie(response)
  File "/app/backend/.venv/lib/python3.11/site-packages/flask_login/login_manager.py", line 482, in _set_cookie
    data = encode_cookie(str(session["_user_id"]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/.venv/lib/python3.11/site-packages/flask_login/utils.py", line 40, in encode_cookie
    return f"{payload}|{_cookie_digest(payload, key=key)}"
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/.venv/lib/python3.11/site-packages/flask_login/utils.py", line 378, in _cookie_digest
    key = _secret_key(key)
          ^^^^^^^^^^^^^^^^
  File "/app/backend/.venv/lib/python3.11/site-packages/flask_login/utils.py", line 413, in _secret_key
    key = key.encode("latin1")  # ensure bytes
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'latin-1' codec can't encode character '\u201c' in position 0: ordinal not in range(256)
```

**Comment by mariusandra** [comment]
Hey, I just tried on my own Synology, and it all seems to work.

I used these settings. Notably I mounted `/app/db` somewhere, to be able to backup the sqlite database, and exposed port 8989 locally.

<img width="678" alt="Screenshot 2024-07-22 at 00 57 17" src="https://github.com/user-attachments/assets/8219b2fb-5747-4075-8c9f-5ce2d771d4db">

I was able to make an account, and login just fine:
<img width="582" alt="Screenshot 2024-07-22 at 00 58 52" src="https://github.com/user-attachments/assets/fdf213bb-b05f-4c1d-ae55-465d675fe85a">
<img width="488" alt="Screenshot 2024-07-22 at 00 59 16" src="https://github.com/user-attachments/assets/3aa29a61-9de1-498f-afec-64cfd26a792e">

I then added a frame and that worked too. I didn't try deploying.

I assume it would work without mounting a folder as well, but then you have the risk of losing all your changes when you restart the container.

I also saw something called Web Station when setting it up. I didn't try it, but as long as it proxies websockets correctly, I don't see why it shouldn't work.

Is there anything you're doing differently from the steps above?

**Comment by mscottco** [comment]
Strange.... I deleted the image, re-downloaded and re-created the container and it works! No idea what happened there but thanks for the help!

FWIW, I'd also tried creating the container on a spare Pi I have running docker and had the same issue so maybe there was a faulty container build or something.
